name: hybridurb
channels:
  - conda-forge
dependencies:
  - python=3.8.*
  - pip
  - poetry
  - networkx=3.0
  - hydromt=0.6.0
  - pytest=7.2.1
  - scikit-learn=1.2.0
  - sympy=1.11.1
  - statsmodels=0.13.5
