global:
  root: ../../data/Eindhoven
  region: ../../data/Eindhoven/region.geojson
  crs: 28992
get_geoms_from_model:
  model_root: ../../data/Eindhoven/Delft3DFM
  mdu_fn: dflowfm/FLOWFM.mdu
setup_networkmodel:
  global:
    snap_offset: 1