name: hybridurb-dev
channels:
  - conda-forge
dependencies:
  - python=3.9.*
  - pip
  - flit>=3.4
  - hydromt>=0.7.0 
  
  - networkx=3.0 # for graph model
  - momepy # for graph model
  
  - scikit-learn # for regression model
  - sympy # for regression model
  - statsmodels # for regression model
  
  - matplotlib # for report

  - pytest # tests
  - pytest-cov # tests
  - pytest-mock # tests
  - pytest-timeout # test
  - responses # tests

  - sphinx # docs
  - sphinx-design # docs
  - pydata-sphinx-theme  # docs
 
  - pip:
    - hydrolib-core==0.5.2
    - git+https://github.com/Deltares/hydromt_delft3dfm.git # for delft3dfm model
    
    - meshkernel  # to run model in operational mode
    - xugrid  # to run model in operational mode
    
