name: hybridurb-dev-test

channels:
  - conda-forge

dependencies:
  - pip
  - flit>=3.4
  - hydromt>=0.9.0 
  
  - networkx # for graph model
  - momepy # for graph model
  
  - scikit-learn # for regression model
  - sympy # for regression model
  - statsmodels # for regression model
  
  # - pygraphviz # for report
  - matplotlib # for report

  - pytest # tests
  - pytest-cov # tests
  - pytest-mock # tests
  - pytest-timeout # test
  - responses # tests

  - sphinx # docs
  - sphinx-design # docs
  - pydata-sphinx-theme  # docs
 
  - pip:
    - hydromt-delft3dfm>=0.2.0 # for delft3dfm model
    - meshkernel  # to run model in operational mode
    - xugrid  # to run model in operational mode

