name: hybridurb-dev-test

channels:
  - conda-forge

dependencies:
  - python=3.11
  - pip
  - flit>=3.4
  - hydromt>=0.9.0 
  
  - networkx # for graph model
  - momepy # for graph model
  
  - scikit-learn # for regression model
  - sympy # for regression model
  - statsmodels # for regression model
  
  # - pygraphviz # for report
  - matplotlib # for report

  - pytest # tests
  - pytest-cov # tests
  - pytest-mock # tests
  - pytest-timeout # test
  - responses # tests

  - sphinx # docs
  - sphinx-design # docs
  - pydata-sphinx-theme  # docs
 
  - pip:
    - git+https://github.com/Deltares/hydromt_delft3dfm.git # for delft3dfm model, temporary pin for 0.2.0.dev0
    - meshkernel  # to run model in operational mode
    - xugrid  # to run model in operational mode

