name: CI

on: [push]

jobs:
  Test:
    name: ${{ matrix.os }} - py${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8]
        os: [windows-latest]
    
    steps:
    - uses: actions/checkout@v2
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge, defaults
        channel-priority: strict
        environment-file: envs/environment_dev.yaml
        activate-environment: hybridurb-dev
        auto-activate-base: false
    
    - name: Conda info
      run: |
       conda info
       conda list
      
    - name: Run image
      uses: abatilo/actions-poetry@v2.0.0
      with:
        poetry-version: 1.3.1
      
    - name: Install Dependencies
      run: poetry install

    - name: Check style
      run: black --check .
        
    #- name: Test with pytest
    #  run: poetry run pytest

    - name: Autoformat code if the check fails
      if: ${{ (matrix.os == 'windows-latest') && (matrix.python-version == 3.8) }}
      run: |
        poetry run isort .
        poetry run black .
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit -am "autoformat: isort & black" && git push || true
