name: Python Package using Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.11]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install hydromt_delft3dfm
      run: |
        python -m pip install --upgrade pip
        python -m pip install hydromt-delft3dfm
        hydromt --models
     
    - name: Install HybridUrb
      run: |
        python -m pip install -e .
        python -c "import hybridurb" || { echo 'hybridurb package not installed correctly'; exit 1; }
        python -m hybridurb.runners.main --help
        
    - name: Test with pytest
      run: python -m pytest

    - name: Autoformat 
      if: ${{ matrix.os == 'windows-latest' && matrix.python-version == 3.11 }}
      run: |
        python -m isort .
        python -m black .
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit -am "autoformat: isort&black" && git push || echo "Autoformat step failed. Please check the logs."
