name: Python Package using Conda

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5
      matrix:
        python-version: [3.11]
        os: [windows-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge, defaults
        channel-priority: strict
        environment-file: envs/environment_dev.yaml
        activate-environment: hybridurb-dev

    - name: Conda info
      run: |
       conda info
       conda list
     
    - name: HybridUrb
      run: |
        python -m pip install .
        python -m hybridurb.runners.main --help
        
    - name: Test with pytest
      run: python -m pytest

    - name: Autoformat 
      if: ${{ (matrix.os == 'windows-latest') && (matrix.python-version == 3.11) }}
      run: |
        python -m black .
        git config --global user.name '${{ github.actor }}'
        git config --global user.email '${{ github.actor }}@users.noreply.github.com'
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git checkout $GITHUB_HEAD_REF
        git commit -am "autoformat: black" && git push || true
