name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: "3.11"
        channels: conda-forge
        channel-priority: strict
        conda-remove-defaults: "true"
    
    - name: Install hydromt-delft3dfm
      run: |
        pip install --upgrade pip
        pip install hydromt-delft3dfm
    
    - name: Install hybridurb
      run: |
        pip install -e .

    - name: Build docs
      run: flit install
    - name: Sphinx build
      run: |
        sphinx-build docs _build
    
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
