name: Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docs:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: "3.11"
        miniforge-variant: Mambaforge
        channels: conda-forge, defaults
        channel-priority: strict
        environment-file: envs/environment_dev.yaml
        activate-environment: hybridurb-dev
    - name: Install hybridurb
      run: flit install
    - name: Sphinx build
      run: |
        sphinx-build docs _build
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      with:
        publish_branch: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: _build/
        force_orphan: true
