name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        miniforge-variant: Mambaforge
        channels: conda-forge, defaults
        channel-priority: strict
        environment-file: environment.yaml
        activate-environment: hybridurb

    - name: Conda info
      run: |
       conda info
       conda list
     
    - name: HybridUrb
      run: python -m hybridurb.runners.main --help
      
     
